### ISSUE TITLE
Show greetings.js after connection and backup

### ISSUE THREAD

**Issue by alexvandesande** [UniversalLogin/UniversalLoginSDK#105]
After the user has his connection approved, and after they have recovered from backup, they should be redirected to greeting view. 

The greetings View should also reflect the current state of token granted: instead of saying "you'll get x tokens for doing N" it should say "you did N and got x tokens for it"

**Comment by Kyrrui** [comment]
@alexvandesande this is finished right? Can I close?

**Comment by alexvandesande** [comment]
Has it been merged elsewhere? Have to ping marek

**Comment by marekkirejczyk** [comment]
I guess we are talking about [PR115](https://github.com/UniversalLogin/UniversalLoginSDK/pull/115),
