### ISSUE TITLE
Integrate Dapparatus Transaction Load Bars

### ISSUE THREAD

**Issue by Kyrrui** [UniversalLogin/UniversalLoginSDK#131]
I was talking with @austingriffith here at DEVCON4 and I think we should add his transaction loader to the UI (especially for mainnet when the user has no idea when transactions will go through). A little work needs to be done on the dapparatus side, but I will talk with Austin about this.

**Comment by marekkirejczyk** [comment]
Do you have a link to the loader?

**Comment by austintgriffith** [comment]
The loading bars are a small piece of a much bigger set of React components known as Dapparatus. Happy to help with any integration and would love collaboration. The repo is here: https://github.com/austintgriffith/dapparatus and there are a few others that are spinning up to help with the project too.

**Comment by austintgriffith** [comment]
The transaction and block time loader bars are located in the <Transactions /> component. They try to predict how long a tx or block will take: https://github.com/austintgriffith/dapparatus/blob/master/src/transactions.js This component also exposes a tx() function for the developer. This allows the dev to simply pass the call in and get a callback and the function itself is smart enough to determine if they are making a meta transaction or if they can afford a read tx.

**Comment by austintgriffith** [comment]
You can watch a live demo where I bring this component and many others in to create a gasless experience for the end user where the developer remains agnostic to their behavior. It was presented as a workshop at devcon4: https://medium.com/@austin_48503/buidlguidl-0x2-meta-transactions-be3ea1d076a6
