### ISSUE TITLE
Quick example does not work using multiple devices

### ISSUE THREAD

**Issue by canepat** [UniversalLogin/UniversalLoginSDK#132]
Hi all,

I've watched a couple of talks by @alexvandesande about Universal Login and I'm really interested in the project which looks great.

I've forked and launched the quick example obtaining a strange behavior, which seems an error, when using multiple devices. After activating the example using `yarn dev:start` on my desktop machine, I can create new identity from a local browser but cannot create or connect from a remote browser (e.g. smartphone or laptop): when typing the username no suggestion is proposed and I see the following errors in the browser console:

![image](https://user-images.githubusercontent.com/16927169/47953142-97771200-df79-11e8-91d8-a7b94c50199a.png)

I've added an optional command line argument to `dev-start.js` script, specifying the HTTP address to use in Ganache and Relayer service URLs and passing one of the host interfaces it works. It's a simple solution but maybe it could be acceptable for the development example.

If this approach sounds good to you, I can submit a small PR with such changes, also describing the optional parameter in the tutorial.

Tullio

**Comment by marekkirejczyk** [comment]
Sounds good! 
Alternatively, we could prepare a docker.

Looking forward to your contributors.
