### ISSUE TITLE
Demo at https://example.universallogin.io/ can't create account

### ISSUE THREAD

**Issue by Ramarti** [UniversalLogin/UniversalLoginSDK#197]
**What i did:**
1. Input a name following the example given in the ui, like:
yo.workthistime.eth
(tried several others later)
2. Click on "create"

**What I expected to happen**
The identity to be created and the demo to proceed.

**What happened**
See next screen for a fraction of a second, then:
<img width="1364" alt="captura de pantalla 2019-01-16 a las 10 43 29" src="https://user-images.githubusercontent.com/2632384/51240556-3c4f9b80-197c-11e9-902f-3885ea9fd005.png">
`Failed to load resource: the server responded with a status of 404 ()
universal-login-relayer.herokuapp.com/identity:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
rinkeby.infura.io/:1 Failed to load resource: net::ERR_NETWORK_CHANGED
ethers.min.js:1 Uncaught (in promise) Error: invalid response - 0
    at XMLHttpRequest.a.onreadystatechange (ethers.min.js:1)
universal-login-relayer.herokuapp.com/identity:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

`
**Request**
curl 'https://universal-login-relayer.herokuapp.com/identity' -H 'Referer: https://example.universallogin.io/' -H 'Origin: https://example.universallogin.io' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' -H 'Content-Type: application/json; charset=utf-8' --data-binary '{"managementKey":"0x0948C0a8E2372a67260CAEd307c5C842BbFdf4FA","ensName":"yo.workthistime.eth"}' --compressed

**Response**:
500
{"error":"Error: domain not existing / not universal ID compatible"}
`

**Comment by marekkirejczyk** [comment]
It will only work with the following domains: `poppularapp.test`, `my-id.test`, `my-super-domain.test`.

**Comment by Ramarti** [comment]
Hi!

Thanks for the response, I didn't notice that in the UI, neither in the first screen or the error one (in fact, the example you give , bob.example.eth won't work neither)

Since that may be the first contact people get from this awesome project, I'd suggest making it clearer, using a selector instead of a text input, a message or something that improves the UX.

Cheers!

**Comment by alexvandesande** [comment]
@Ramarti there should be a dropdown visible Could you go back and confirm you have it? I would suspect this is a combination of one of these bugs:

<img width="546" alt="screen shot 2019-01-16 at 10 38 33 am" src="https://user-images.githubusercontent.com/112898/51249604-efb79080-197a-11e9-8b03-668fa8d35907.png">


1) *A technical bug*: for some reason the dropdown is not showing
2) *A usability bug*: you were not expecting a dropdown and typed very fast and pressed enter without giving time for the dropdown to appear. If that's the case, maybe we should disable the "enter" key until the dropdown is visible

**Comment by Ramarti** [comment]
1. Typed "yo" and waited --> Same result, although it does take a little while.

<img width="532" alt="captura de pantalla 2019-01-16 a las 14 18 36" src="https://user-images.githubusercontent.com/2632384/51251551-e1c53800-1999-11e9-9fb1-50a5a5057d59.png">

2. Typed random stuff --> Ok, no option available

<img width="546" alt="captura de pantalla 2019-01-16 a las 14 19 37" src="https://user-images.githubusercontent.com/2632384/51251606-fefa0680-1999-11e9-80b7-cc77630f1107.png">

3. Typed something finished in .eth  --> I have the option to create it.

It appears whatever ends in .eth has the option to be created?

<img width="533" alt="captura de pantalla 2019-01-16 a las 14 19 50" src="https://user-images.githubusercontent.com/2632384/51251671-2a7cf100-199a-11e9-811c-eede6c3095fa.png">

**Comment by alexvandesande** [comment]
yes, we are working on having better fail down mode and showing when name creation is not available. It's not immediately clear which ".eth" names should be allowed because, while on the demo there are only 3 options, we want that any name be able to support it

**Comment by marekkirejczyk** [comment]
Ok, so I guess this is a bug that needs to be fixed.

**Comment by Ramarti** [comment]
I think if the placeholder in the demo was "bob.oneofthesupporteddomains.test" instead of "bob.example.eth", people will tend to just type more in that line.

However if you are already working on a better more general solution it's ok, this is probably not of the highest priority.

Thanks for your responses, I think this project or something similar is critical for mass adoption. 👍

**Comment by marekkirejczyk** [comment]
Closing, fixed by #201.
