### ISSUE TITLE
Addresses for registrars used in relayer 

### ISSUE THREAD

**Issue by Giulio2002** [UniversalLogin/UniversalLoginSDK#224]
i am trying to setup a relayer on rinkeby but i need the resolvers and registrar addresses of each domain, in ENSRegistred.md there is only the public resolver address. is it possible to have the testRegistrars addresses and resolver address of each domain, and maybe add them somewhere in the docs. many thanks in advance.

**Comment by JustynaBroniszewska** [comment]
Hi 😄 , recently we removed resolver and registrar addresses from relayer config. Now, relayer only needs name of each domain. 
Check out [relayer documentation](https://universalloginsdk.readthedocs.io/en/latest/relayer.html) to learn more.
