### ISSUE TITLE
Demo at https://example.universallogin.io/ doesn't load

### ISSUE THREAD

**Issue by dteiml** [UniversalLogin/UniversalLoginSDK#341]
**What I did:**
Typed 'dteiml' into the search box.

**What I expected to happen:**
I get a list of options to create and id.

**What happened:**
It's been loading for 11 minutes:

![this](https://i.imgur.com/WIrUmsR.png)

**Comment by JustynaBroniszewska** [comment]
Hi @dteiml,
thank you for letting us know about this issue. Everything is working now. 😉 
I'm closing this now but feel free to reopen it if anything happens 😄
