### ISSUE TITLE
Contracts refactoring

### ISSUE THREAD

**Issue by marekkirejczyk** [UniversalLogin/UniversalLoginSDK#361]
- [x] new folder structure: ENS, ERC1077, Wallet, common, mock
- [x] extract storage contracts (as base for MasterCopy and Proxy) 
- [x] try to run tests for proxy and master as one suite with two configuration options
- [x] simplify master and proxy implementations
- [x] do we need both 1077 and identity master and proxy?
- [x] merge/remove unnecessary modifiers: `authorised`, `onlyManagementKeyOrThisContract`, `onlyManagementOrActionKeys`
- [x] move erc721 receiver to wallet

**Comment by marekkirejczyk** [comment]
CC @canepat

**Comment by Amxx** [comment]
Can I help with that ?

I have a working branch with erc1836 proxy (https://github.com/Amxx/UniversalLoginSDK/tree/erc1836) and I believe there is some good stuff to take from it. In particular, moving the initialisation logic (that includes ENS registration) to the master to reduce the deployment cost of the proxy.

Also, you should really consider supporting ERC1271 out of the box.

**Comment by Amxx** [comment]
I think my PR solves most of these points. In particular I have the master/proxy switch in the relayer (ENSLegacy uses full contract while the standard deploies a proxy)
