### ISSUE TITLE
Database format change causes relayer error

### ISSUE THREAD

**Issue by Amxx** [UniversalLogin/UniversalLoginSDK#403]
It looks like the pgsql format has changed recently. The database was initialized (on my machine) when I first started using the SDK about 1 month ago and everything was working well until recently.

Creating wallet worked well, but when I tryed to connect to an existing wallet, the new device got an error from the relayer:

    error: "error: insert into \"authorisations\" (\"deviceInfo\", \"key\", \"walletContractAddress\") values ($1, $2, $3) returning \"id\" - la colonne « walletContractAddress » de la relation « authorisations » n'existe pas"

This is french for "column walletContractAddress of relation authorisations doesn't exist".

I managed to solve this by manually dropping the database. When I restarted the relayer I recreated it with the right format. Conclusion is, when starting a relayer, verifying that the database exist is not enough, it is also necessary to check it is in the right format.

**Comment by marekkirejczyk** [comment]
Should be fixed #408
