### ISSUE TITLE
Ethers.js - query returned more than 1000 results. Loading activity stuck

### ISSUE THREAD

**Issue by RobertoSnap** [UniversalLogin/UniversalLoginSDK#455]
In example app at https://example.universallogin.io/ i get this error in console and stuck at "loading activity".

`ethers.min.js:1 Uncaught (in promise) Error: query returned more than 1000 results
    at m (ethers.min.js:1)
    at XMLHttpRequest.a.onreadystatechange (ethers.min.js:1)`

Tested from Chrome and Brave. 

![image](https://user-images.githubusercontent.com/4772930/57223200-95b00900-7005-11e9-994a-3e2efba248ac.png)

**Comment by JustynaBroniszewska** [comment]
Hi, @RobertoSnap ! 
Thanks for this issue! 😉 
Fixed in #456  😄
