### ISSUE TITLE
Relay is undeployable

### ISSUE THREAD

**Issue by Jaypov** [UniversalLogin/UniversalLoginSDK#681]
When running `yarn relayer:start` from the `universal-login-relay` directory there is an error.
a script is missing from the build.

```Error: Cannot find module '/home/vagrant/UniversalLoginSDK/universal-login-relayer/build/lib/startRelayer.js'```

Steps to reproduce:
1. Clone UniversalLoginSDK
2. install tool kit `yarn global add @universal-login/ops`
3. yarn install
4. yarn build 
5. deploy token `universal-login deploy:token --nodeUrl http://localhost:18545 --privateKey 0x29f3edee0ad3abf8e2699402e0e28cd6492c9be7eaab00d732a791c33552f797
`
6. install and configure postgres
7. deploy factory contract `universal-login deploy:factory [walletMasterAddress] --privateKey 'YOUR_PRIVATE_KEY' --nodeUrl 'JSON-RPC URL'
`
8. `cd universal-login-relayer && yarn relayer:start`

**Comment by JustynaBroniszewska** [comment]
Hi @Jaypov 
Thank you for letting us know! Try the latest version of @universal-login (0.3.6). Starting relayer should work fine.
Closing, for now, feel free to reopen. 😉
