### ISSUE TITLE
Unhandled promise rejection in SuggestionService

### ISSUE THREAD

**Issue by msieczko** [UniversalLogin/UniversalLoginSDK#699]
# Issue
[isCorrectPrefix](https://github.com/UniversalLogin/UniversalLoginSDK/blob/cf09234caeb26c70d7ebbe3d27e64c31f50677dd/universal-login-commons/lib/core/services/SuggestionsService.ts#L26) method of SuggestionService returns true for prefix containing underscore (`_`) causing the call to walletContractExist to reject

## Steps to reproduce
1. Start wallet app
2. Type `aaa_` in name input field

## Current behavior
Loader keeps spinning. Uncaught promise is logged: 
>Error: contains invalid UseSTD3ASCIIRules characters

## Expected behavior
Loader stops spinning, no suggestions appear

**Comment by gasiortomasz** [comment]
https://github.com/UniversalLogin/UniversalLoginSDK/pull/837
