### ISSUE TITLE
SuggestionService suggests names which cause deploy() to throw

### ISSUE THREAD

**Issue by msieczko** [UniversalLogin/UniversalLoginSDK#700]
# Issue
[`getSuggestions`](https://github.com/UniversalLogin/UniversalLoginSDK/blob/cf09234caeb26c70d7ebbe3d27e64c31f50677dd/universal-login-commons/lib/core/services/SuggestionsService.ts#L80) method of `SuggestionService` delivers suggestions for names including uppercase characters. Calling `deploy` method of the SDK with such name results in an exception.

## Steps to reproduce
1. Start wallet app.
2. Type `aBc` in name input field.
3. Click `CREATE NEW` next to `aBc.mylogin.eth`.
4. Choose `Deposit crypto`.
5. Transfer funds to the displayed address, e.g. `npx universal-login send 0x6f765a12e2bd96b07bfc4de410a7744664f26157 4 ETH`

## Current behavior
Transaction is stuck pending. Uncaught promise is logged: 
>Error: VM Exception while processing transaction: revert Unable to register ENS domain

## Expected behavior
`aBc.mylogin.eth` doesn't appear on the suggestions list

**Comment by gasiortomasz** [comment]
https://github.com/UniversalLogin/UniversalLoginSDK/pull/837
