### ISSUE TITLE
Links to LGPL-v3-licensed contract dirs broken in README

### ISSUE THREAD

**Issue by pcowgill** [UniversalLogin/UniversalLoginSDK#742]

**Comment by pcowgill** [comment]
I think
[common](https://github.com/UniversalLogin/UniversalLoginSDK/tree/master/universal-login-contracts/contracts/erc1836/common)
and
[proxy](https://github.com/UniversalLogin/UniversalLoginSDK/tree/master/universal-login-contracts/contracts/erc1836/proxy)
are probably the correct links to use now.

**Comment by JustynaBroniszewska** [comment]
Hi @pcowgill 

You are right, links were outdated. Fixed in #745 

Thank you! 😊
