### ISSUE TITLE
Add option to use test network

### ISSUE THREAD

**Issue by alexvandesande** [UniversalLogin/UniversalLoginSDK#94]
It would be very useful for hackatons and other similar spaces if there was an easy `yarn build` option that would use a test network (Rinkeby?) and infura for the connections. In this manner, multiple projects could collaborate, use each other logins, and have a real "multi user" experience.

*priority: low, nice to have*

**Comment by Kyrrui** [comment]
@alexvandesande I would argue more than nice to have... Perhaps we can work on this at the Status hackathon in Prague. I will definitely need this for my work at BoomerangProject.io

**Comment by marekkirejczyk** [comment]
It is in our internal backlog

**Comment by marekkirejczyk** [comment]
This is done.

Register your own relayer domain and start relayer:
https://github.com/UniversalLogin/UniversalLoginSDK/blob/master/universal-login-relayer/README.md

Run example:
https://github.com/UniversalLogin/UniversalLoginSDK/blob/master/universal-login-example/README.md#running-example-on-testnet-environment
