### ISSUE TITLE
Generate backup codes should save the new code

### ISSUE THREAD

**Issue by abcoathup** [UniversalLogin/UniversalLoginSDK#98]
Generate backup codes should save the new code, as currently not obvious to a user that the backup code generated needs to be saved. 

Currently the flow is:
1. Go to Account page
2. Press Backup code button
3. Press Generate New Codes
4. A new code is generated, with instructions to print
5. A user prints the backup code
6. A user needs to press the Set as Backup Codes button before it can be used.

It is not obvious to a user that the backup code hasn't been saved so the last step could be skipped.  A user could potentially print out the code without actually saving the code.  To close the window, they could press Cancel backup code.

Ideally with the Generate New Codes and Generate Another Code there would be a message stating this would cost 2 clicks and this would generate and save the code to avoid users generating, printing a code without saving it.

**Comment by abcoathup** [comment]
UniversalLogin is going to get a lot of visibility and hopefully lots of use soon, so I think this is really important before it starts getting adopted.

I believe that showing a code that isn't saved is highly dangerous. 
Users will assume that the recovery code is live. (I did and then realised that I needed to save it first). 

We will end up with users who thought they had printed a recovery code, stored it safely and when they need to use it, find out the hard way that the code was useless (as it wasn't saved) and their account unrecoverable.

Compare this with the cost that some curious users will pay for a backup code which they may not need after going through messaging.  

At the point of the Backup code button messaging of the cost of the code could be included, for example, and the user has the choice whether to proceed:

_Back up your account_

_If you lose all your devices you may not have other ways to recover your account. Generate a recovery code and keep it safe_

**This will cost 2 clicks**

Adding messaging when attempting to leave the page could still result in users printing a code and then closing the app/browser.  One user with an unsaved code feels like too many.

**Comment by alexvandesande** [comment]
> One user with an unsaved code feels like too many.

I agree. I will try to think about ways to make this process more clear, with more warnings before the user leaves it, a dedicated print button, etc

**Comment by Kyrrui** [comment]
@abcoathup @alexvandesande Let me know if you'd like to re-open this issue, closing for now to keep the repo clean as conversations seems resolved for now.

**Comment by abcoathup** [comment]
@kyrrui Whilst the example app still has the potential for users to end up with recovery codes that they haven’t saved then I believe we should keep it open until resolved.

**Comment by abcoathup** [comment]
I’ll have a look when I get back to Australia (just waiting to take off). 

A warning could still end up with users with codes printed and stored away thinking they are safe but the codes are not saved. 

I still strongly believe the example app (which developers will use as best practice) should not show codes until they are saved onchain.

**Comment by sergchernata** [comment]
> I would suggest other layouts. Maybe showing an alert when trying to leave the page, or some sort of "this is not saved yet" message.

What if you change the actual interaction and charge the user only when they save? This feels like too many steps overall. Something needs to be combined.

Also, in the demo each code has a username shown above the code, repeated 3 times. I know that it's to encourage cutting out of the individual codes, but imo the user is more likely to print the page 3 times or simply save it as a PDF. This could be simplified down to 1 display of the username and all codes listed below it. Listing the username 3 times is a bit too much to look at.
