### ISSUE TITLE
Creating a new login for a domain that doesn't exist should fail nicely

### ISSUE THREAD

**Issue by abcoathup** [UniversalLogin/UniversalLoginSDK#99]
If you create a new login for a domain that doesn't exist, then the app keeps showing Creating ID page.

1. In the login, type bob.notexists.eth
2. Press the create button to create login bob.notexists.eth
3. App shows Creating ID page

Ideally creating a new login for a domain that doesn't exist should fail nicely with some sort of message that login notexists.eth doesn't exist or couldn't be found.

**Comment by marekkirejczyk** [comment]
It is in our internal backlog

**Comment by canepat** [comment]
@marekkirejczyk I would like to contribute on this issue if no one is already working on it.

As a start I would post a brief analysis with my comprehension of the problem and the proposed solution for review

**Comment by marekkirejczyk** [comment]
@canepat Looking forward to your PR. Let me know if you would like to schedule a short call to discuss it.

**Comment by marekkirejczyk** [comment]
Fixed by [143](https://github.com/UniversalLogin/UniversalLoginSDK/pull/143)
